Sprint 6 solution
a-buianova/java-kanban pull request #1
Opened 2024-12-02 13:01 UTC by a-buianova

2024-12-03 19:00 UTC, Fleaman777 requested changes

2024-12-04 13:55 UTC, a-buianova commented on src/manager/InMemoryTaskManager.java
> +        return List.of();
Точно. Спасибо!

2024-12-04 14:04 UTC, a-buianova commented on test/manager/HistoryManagerTest.java
>      }
Спасибо за важное замечание! Исправила

2024-12-04 18:31 UTC, a-buianova commented on src/manager/TaskManager.java
> +    void removeEpic(int id);
Исправила. Спасибо!

2024-12-05 12:40 UTC, Fleaman777 approved these changes

2025-02-17 17:05 UTC, merged